    <header>
        <a href=""><img src="../assets/img/logo-gT.png" alt="GainTime"></a>
        <input type="checkbox" id="menu" class="toggle">
        <label id="menu-toggle" for="menu" onclick><i class="fa fa-bars"></i></label>
        <nav class="menu">
            <ul>
                <a href="news.php"><li><i class="fa fa-newspaper-o"></i> Notícias</li></a>
                <a href="files.php"><li><i class="fa fa-file-pdf-o"></i> Arquivos</li></a>
                <a href="users.php"><li><i class="fa fa-user"></i> Usuários</li></a>
                <a href="contact.php"><li><i class="fa fa-user"></i> Contato</li></a>
                <a href="login.php"><li><i class="fa fa-sign-out"></i> Sair</li></a>
            </ul>
        </nav>
    </header>
